### ISSUE TITLE
Allow disabling specific keymap

### ISSUE THREAD

**Issue by Shatur** [Tummetott/unimpaired.nvim#2]
It would be great to allow it. For example, I prefer to use `]t` for `:tabnext` instead of `:tnext`. So I would like to disable the built-in keymapping. I would like to suggest to support something like this:

```lua
require('unimpaired').setup({
  keymaps = {
    tnext = false,
    tfirst = false,
  },
})
```

**Comment by Shatur** [comment]
Alternatively we could allow to override the used command.

**Comment by tummetott** [comment]
Sorry for my late reply, i was incredible busy.

It's already possible to disable build-in keymappings. Just read the `README`

https://github.com/tummetott/unimpaired.nvim/blob/3a3993eb2d8df48dac691876751e80cccb395880/.github/README.md?plain=1#L79-L80

After you disabled it, you can remap the keys however you like
