### ISSUE TITLE
Default configuration for `cursorcolumn` is doubled up

### ISSUE THREAD

**Issue by linduxed** [Tummetott/unimpaired.nvim#3]
This section seems to have the three keys doubled up. It's unclear which of the two binding letters (`t` or `u`) that should be used.

https://github.com/tummetott/unimpaired.nvim/blob/3a3993eb2d8df48dac691876751e80cccb395880/lua/unimpaired/config.lua#L311-L340

**Comment by tummetott** [comment]
Did you maybe misread the section? `cursorcolumn` and `colorcolumn` are two different settings. Check the vim documentation what they do.

**Comment by linduxed** [comment]
Indeed, I must have just misread the section, these are clearly two different words. I'm not sure how I made this mistake. Thanks for pointing it out!
