### ISSUE TITLE
`]f` differs from vim-unimpaired

### ISSUE THREAD

**Issue by UnkwUsr** [Tummetott/unimpaired.nvim#4]
In vim-unimpaired `]f` and `[f` can traverse between directories (<https://github.com/tpope/vim-unimpaired/issues/227>), while this plugin limited only to files of current directory.

I'm wondering if this is intended behavior, and if not, is it planned to be fixed? (P.S. to be honest, right now I'm trying to get rid of vim-unimpaired exactly because of his "confusing" (at least for me) behavior)

**Comment by tummetott** [comment]
This is intended and I don't plan change the implementation. I find it very confusing if one can ascent / descent the directory. I rather use a fuzzy search or a directory tree plugin for that.
